- heading "TeamQa" [level=6]
- text: STIR 983154321
- button "Yopish"
- button "Yashirish"
- region "scrollable content":
  - navigation:
    - list:
      - listitem:
        - list:
          - listitem:
            - link "Главная":
              - /url: /dashboard
      - listitem:
        - list:
          - listitem:
            - button "Документооборот"
      - listitem:
        - list:
          - listitem:
            - button "Оргструктура"
      - listitem:
        - list:
          - listitem:
            - button "Настройки"
- separator
- button "Switch language to O'zbekcha": RU
- button "Toggle theme"
- separator
- button "User menu":
  - text: +
  - paragraph: "+998913030519"
  - text: Администратор
- main:
  - heading "Шаблоны маршрутов" [level=4]
  - paragraph: 1 маршрутов
  - button "Создать маршрут"
  - textbox "Поиск по названию..."
  - table:
    - rowgroup:
      - row "Название Шаги Статус Version Последнее изменение Действия":
        - columnheader "Название"
        - columnheader "Шаги"
        - columnheader "Статус"
        - columnheader "Version"
        - columnheader "Последнее изменение"
        - columnheader "Действия"
    - rowgroup:
      - row "Увольнение Увольнение 2 Активный v2 01.05.2026 edit Удалить":
        - cell "Увольнение Увольнение":
          - paragraph: Увольнение
          - text: Увольнение
        - cell "2":
          - paragraph: "2"
        - cell "Активный"
        - cell "v2":
          - paragraph: v2
        - cell "01.05.2026":
          - paragraph: 01.05.2026
        - cell "edit Удалить":
          - button "edit"
          - button "Удалить"
  - paragraph: "Записей на странице:"
  - 'combobox "Записей на странице: 25"': "25"
  - paragraph: 1–1 из 1
  - button "Go to previous page" [disabled]
  - button "Go to next page" [disabled]
- region "Notifications alt+T"